name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
      - master

env:
  REPO_URL: 889321718134.dkr.ecr.eu-west-1.amazonaws.com/ecs-demo-customer
  REPOSITORY: ${{ env.REPO_URL%/* }}
  COMMIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Logging in to Amazon ECR
        run: |
          echo Logging in to Amazon ECR...
          # aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.REPOSITORY }}
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 889321718134.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: |
          echo Build started on $(date)
          echo Building the Docker image...
          # docker build -t ${{ env.REPO_URL }} ${{ env.FOLDER_PATH }}
          docker build -t ecs-demo-customer .

      - name: Push Docker image
        run: |
          echo Build completed on $(date)
          echo Pushing the Docker image...
          # docker tag ${{ env.REPO_URL }} ${{ env.REPO_URL }}:${{ env.COMMIT_HASH }}
          docker tag ecs-demo-customer:latest 889321718134.dkr.ecr.eu-west-1.amazonaws.com/ecs-demo-customer:${{ env.COMMIT_HASH }}

          docker push ${{ env.REPO_URL }}:${{ env.COMMIT_HASH }}

      - name: Prepare spec files
        run: |
          echo Preparing spec files in new folder
          mkdir artifacts
          printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "${{ env.REPO_URL }}:${{ env.COMMIT_HASH }}" > artifacts/imagedefinitions.json
          cat artifacts/imagedefinitions.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: artifacts
